# challenge 1

In [3]:
import pandas as pd

books = pd.DataFrame({
    'title': ['The Pragmatic Programmer', 'Clean Code', 'Python Crash Course',
              'Data Science from Scratch', 'Designing Data-Intensive Apps'],
    'author': ['Hunt & Thomas', 'Robert Martin', 'Eric Matthes',
               'Joel Grus', 'Martin Kleppmann'],
    'genre': ['Tech', 'Tech', 'Tech', 'Data', 'Data'],
    'price': [45.99, 38.50, 29.99, 42.00, 55.00],
    'units_sold': [120, 95, 200, 80, 60],
    'in_stock': [True, True, False, True, False]
})

books

,title,author,genre,price,units_sold,in_stock
0,The Pragmatic Programmer,Hunt & Thomas,Tech,45.99,120,True
1,Clean Code,Robert Martin,Tech,38.50,95,True
2,Python Crash Course,Eric Matthes,Tech,29.99,200,False
3,Data Science from Scratch,Joel Grus,Data,42.00,80,True
4,Designing Data-Intensive Apps,Martin Kleppmann,Data,55.00,60,False

In [4]:
books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       5 non-null      object
 1   author      5 non-null      object
 2   genre       5 non-null      object
 3   price       5 non-null      float64
 4   units_sold  5 non-null      int64
 5   in_stock    5 non-null      bool
dtypes: bool(1), float64(1), int64(1), object(3)
memory usage: 333.0+ bytes

In [5]:
books.describe()

           price  units_sold
count   5.000000    5.000000
mean   42.296000  111.000000
std     9.232715   54.359912
min    29.990000   60.000000
25%    38.500000   80.000000
50%    42.000000   95.000000
75%    45.990000  120.000000
max    55.000000  200.000000

In [6]:
books['revenue'] = books['price'] * books['units_sold']
books

,title,author,genre,price,units_sold,in_stock,revenue
0,The Pragmatic Programmer,Hunt & Thomas,Tech,45.99,120,True,5518.8
1,Clean Code,Robert Martin,Tech,38.50,95,True,3657.5
2,Python Crash Course,Eric Matthes,Tech,29.99,200,False,5998.0
3,Data Science from Scratch,Joel Grus,Data,42.00,80,True,3360.0
4,Designing Data-Intensive Apps,Martin Kleppmann,Data,55.00,60,False,3300.0

In [7]:
# What is the total revenue across all books?
total_revenue = books['revenue'].sum()
total_revenue

21834.3

# challenge 2

In [8]:
# 1. Use `.loc` to select only `title` and `revenue` for Data genre books.
# books['genere'] == 'Data'
#books.loc[books['genre'] == 'Data']
books.loc[books['genre'] == 'Data', ['title', 'revenue']]

                           title  revenue
3      Data Science from Scratch   3360.0
4  Designing Data-Intensive Apps   3300.0

In [9]:
# 2. Use `.iloc` to retrieve the last 3 rows and first 3 columns.
books.iloc[-3:, :3]

                           title            author genre
2            Python Crash Course      Eric Matthes  Tech
3      Data Science from Scratch         Joel Grus  Data
4  Designing Data-Intensive Apps  Martin Kleppmann  Data

In [10]:
# 3. Filter books that are **in stock** AND have a **price above £40**.
# books.loc[books['in_stock'] & books['price']>40.0]
books.loc[books['in_stock'] & (books['price']>40.0)]

,title,author,genre,price,units_sold,in_stock,revenue
0,The Pragmatic Programmer,Hunt & Thomas,Tech,45.99,120,True,5518.8
3,Data Science from Scratch,Joel Grus,Data,42.00,80,True,3360.0

In [11]:
# 4. Find the book with the **highest revenue** using `.loc` with `.idxmax()`.
highest_revenue_book = books.loc[books['revenue'].idxmax()]
highest_revenue_book

title         Python Crash Course
author               Eric Matthes
genre                        Tech
price                       29.99
units_sold                    200
in_stock                    False
revenue                    5998.0
Name: 2, dtype: object

# challenge 3

In [12]:
# Use .apply() to add a price_tier column: 'Budget' (< £35), 'Standard' (£35–£50), 'Premium' (> £50).
def tiering(row):
    if row['price'] < 35:
        return 'Budget'
    elif 35 <= row['price'] <= 50:
        return 'Standard'
    else:
        return 'Premium'
    

books['price_tier']=books.apply(tiering, axis=1)
books

,title,author,genre,price,units_sold,in_stock,revenue,price_tier
0,The Pragmatic Programmer,Hunt & Thomas,Tech,45.99,120,True,5518.8,Standard
1,Clean Code,Robert Martin,Tech,38.50,95,True,3657.5,Standard
2,Python Crash Course,Eric Matthes,Tech,29.99,200,False,5998.0,Budget
3,Data Science from Scratch,Joel Grus,Data,42.00,80,True,3360.0,Standard
4,Designing Data-Intensive Apps,Martin Kleppmann,Data,55.00,60,False,3300.0,Premium

In [13]:
# Sort the DataFrame by revenue descending.
books.sort_values('revenue', ascending=False, inplace=True)
books

,title,author,genre,price,units_sold,in_stock,revenue,price_tier
2,Python Crash Course,Eric Matthes,Tech,29.99,200,False,5998.0,Budget
0,The Pragmatic Programmer,Hunt & Thomas,Tech,45.99,120,True,5518.8,Standard
1,Clean Code,Robert Martin,Tech,38.50,95,True,3657.5,Standard
3,Data Science from Scratch,Joel Grus,Data,42.00,80,True,3360.0,Standard
4,Designing Data-Intensive Apps,Martin Kleppmann,Data,55.00,60,False,3300.0,Premium

In [14]:
# Add a sales_rank column using .rank(ascending=False).
books['sales_rank'] = books['revenue'].rank(ascending=False)
books

,title,author,genre,price,units_sold,in_stock,revenue,price_tier,sales_rank
2,Python Crash Course,Eric Matthes,Tech,29.99,200,False,5998.0,Budget,1.0
0,The Pragmatic Programmer,Hunt & Thomas,Tech,45.99,120,True,5518.8,Standard,2.0
1,Clean Code,Robert Martin,Tech,38.50,95,True,3657.5,Standard,3.0
3,Data Science from Scratch,Joel Grus,Data,42.00,80,True,3360.0,Standard,4.0
4,Designing Data-Intensive Apps,Martin Kleppmann,Data,55.00,60,False,3300.0,Premium,5.0

In [15]:
# Use .map() to encode genre as a number: {'Tech': 0, 'Data': 1}.
books['genre_code'] = books['genre'].map({'Tech':0,'Data':1})
books

,title,author,genre,price,units_sold,in_stock,revenue,price_tier,sales_rank,genre_code
2,Python Crash Course,Eric Matthes,Tech,29.99,200,False,5998.0,Budget,1.0,0
0,The Pragmatic Programmer,Hunt & Thomas,Tech,45.99,120,True,5518.8,Standard,2.0,0
1,Clean Code,Robert Martin,Tech,38.50,95,True,3657.5,Standard,3.0,0
3,Data Science from Scratch,Joel Grus,Data,42.00,80,True,3360.0,Standard,4.0,1
4,Designing Data-Intensive Apps,Martin Kleppmann,Data,55.00,60,False,3300.0,Premium,5.0,1

# stretch

### 1. test
### 2. test

In [16]:
# The manager wants a report comparing average price and total revenue by `price_tier`. 
# Use `groupby()` to generate this summary. Which tier contributes the most total revenue despite having the lowest average price?

# report = books.groupby('price_tier').agg({'price':'mean', 'revenue':'sum'})
report = books.groupby('price_tier')
report.describe()
report.agg({'price':'mean', 'revenue':'sum'})

                price  revenue
price_tier
Budget      29.990000   5998.0
Premium     55.000000   3300.0
Standard    42.163333  12536.3